# Generated by Django 4.2.7 on 2023-12-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='document_scan',
            field=models.FileField(upload_to='photos/certificate/', verbose_name='Скан документа'),
        ),
        migrations.AlterField(
            model_name='certificateattachment',
            name='document_scan',
            field=models.FileField(upload_to='photos/certificate_attachment/', verbose_name='Скан документа'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='document_scan',
            field=models.FileField(upload_to='photos/contract/', verbose_name='Скан документа'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='photo',
            field=models.ImageField(upload_to='photos/medicine/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='document_scan',
            field=models.FileField(upload_to='photos/prescription/', verbose_name='Скан документа'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='photos/profile/', verbose_name='Фото'),
        ),
    ]
