# Generated by Django 4.2.7 on 2023-12-23 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_contract_supplier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['number', 'physical_person'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['date', 'contract'], 'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_visit_date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medical_facility',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pharmacy_visit_date',
            field=models.DateField(verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateField(verbose_name='Дата рецепта'),
        ),
        migrations.CreateModel(
            name='PrescComposition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dosage', models.CharField(max_length=255, verbose_name='Дозировка')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.medicine', verbose_name='Препарат')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.prescription', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Состав рецепта',
                'verbose_name_plural': 'Составы рецептов',
                'db_table': 'PrescComposition',
            },
        ),
    ]
